name: TokenX Build & Release - Canary build

on:
  push:
    tags:
      - 'canary-v*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  prepare-runtime:
    name: Prepare Runtime Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download hf-bridge artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: hf-bridge.yml
          workflow_conclusion: success
          path: runtime-artifacts

      - name: Prepare runtime assets
        shell: bash
        run: |
          set -euo pipefail
          RUNTIMES_DIR="src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace/runtimes"
          rm -rf "${RUNTIMES_DIR}"
          mkdir -p "${RUNTIMES_DIR}"
          TEMP_DIR="$(mktemp -d)"

          shopt -s nullglob
          mapfile -d '' -t archives < <(find runtime-artifacts -type f \( -name '*.tar.gz' -o -name '*.zip' \) -print0)

          if [ ${#archives[@]} -eq 0 ]; then
            echo "No runtime archives found under runtime-artifacts" >&2
            exit 1
          fi

          for archive in "${archives[@]}"; do
            base="$(basename "${archive}")"
            stem="${base}"
            workdir="${TEMP_DIR}/${stem}"

            if [[ "${archive}" == *.tar.gz ]]; then
              stem="${base%.tar.gz}"
              workdir="${TEMP_DIR}/${stem}"
              mkdir -p "${workdir}"
              tar -xzf "${archive}" -C "${workdir}"
            elif [[ "${archive}" == *.zip ]]; then
              stem="${base%.zip}"
              workdir="${TEMP_DIR}/${stem}"
              mkdir -p "${workdir}"
              unzip -oq "${archive}" -d "${workdir}"
            else
              echo "Skipping unsupported artifact ${base}"
              continue
            fi

            case "${stem}" in
              tokenx-bridge-*-x86_64-unknown-linux-gnu)
                dest="linux-x64/native"
                ;;
              tokenx-bridge-*-x86_64-pc-windows-msvc)
                dest="win-x64/native"
                ;;
              tokenx-bridge-*-x86_64-apple-darwin)
                dest="osx-x64/native"
                ;;
              tokenx-bridge-*-aarch64-apple-darwin)
                dest="osx-arm64/native"
                ;;
              tokenx-bridge-*-aarch64-apple-ios)
                dest="ios-arm64/native"
                ;;
              tokenx-bridge-*-aarch64-linux-android)
                dest="android-arm64/native"
                ;;
              tokenx-bridge-*-coverage)
                echo "Skipping coverage artifact ${stem}"
                continue
                ;;
              runtime-*)
                dest="${stem#runtime-}/native"
                ;;
              *)
                echo "Skipping unrecognized artifact ${stem}"
                continue
                ;;
            esac

            mkdir -p "${RUNTIMES_DIR}/${dest}"
            find "${workdir}" -maxdepth 1 -type f -exec cp {} "${RUNTIMES_DIR}/${dest}/" \;
          done

          echo "Resolved runtime assets:"
          find "${RUNTIMES_DIR}" -maxdepth 3 -type f

      - name: Package runtime assets
        run: |
          tar -czf tokenizers-runtimes.tar.gz -C src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace runtimes

      - name: Upload runtime assets
        uses: actions/upload-artifact@v4
        with:
          name: tokenizers-hf-runtimes
          path: tokenizers-runtimes.tar.gz
          if-no-files-found: error

  build:
    name: Build Solution
    runs-on: ubuntu-latest
    needs: prepare-runtime
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download runtime assets
        uses: actions/download-artifact@v4
        with:
          name: tokenizers-hf-runtimes
          path: runtime-assets

      - name: Restore runtime assets
        run: |
          RUNTIMES_ROOT="src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace"
          rm -rf "${RUNTIMES_ROOT}/runtimes"
          mkdir -p "${RUNTIMES_ROOT}"
          tar -xzf runtime-assets/tokenizers-runtimes.tar.gz -C "${RUNTIMES_ROOT}"

      - name: Restore tokenizer fixtures
        shell: bash
        run: |
          set -euo pipefail
          python3 tests/Py/Huggingface/restore_test_data.py --force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build TokenX.HF.sln --configuration Release --no-restore

  unit-tests:
    name: Run Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    defaults:
      run:
        shell: bash
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download runtime assets
        uses: actions/download-artifact@v4
        with:
          name: tokenizers-hf-runtimes
          path: runtime-assets

      - name: Restore runtime assets
        run: |
          RUNTIMES_ROOT="src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace"
          rm -rf "${RUNTIMES_ROOT}/runtimes"
          mkdir -p "${RUNTIMES_ROOT}"
          tar -xzf runtime-assets/tokenizers-runtimes.tar.gz -C "${RUNTIMES_ROOT}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore tokenizer fixtures
        shell: bash
        run: |
          set -euo pipefail
          python tests/Py/Huggingface/restore_test_data.py --force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build TokenX.HF.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test TokenX.HF.sln --configuration Release --no-build --logger "trx;LogFileName=unit-tests.trx" --filter "TestCategories=Unit"

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: canary-unit-test-results-${{ matrix.os }}
          path: tests/**/TestResults/*.trx
          if-no-files-found: ignore

  integration-tests:
    name: Run Integration Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    defaults:
      run:
        shell: bash
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download runtime assets
        uses: actions/download-artifact@v4
        with:
          name: tokenizers-hf-runtimes
          path: runtime-assets

      - name: Restore runtime assets
        run: |
          RUNTIMES_ROOT="src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace"
          rm -rf "${RUNTIMES_ROOT}/runtimes"
          mkdir -p "${RUNTIMES_ROOT}"
          tar -xzf runtime-assets/tokenizers-runtimes.tar.gz -C "${RUNTIMES_ROOT}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Provision Python environment
        shell: bash
        run: |
          set -euo pipefail
          python -m venv .venv
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          python -m pip install --upgrade pip
          python -m pip install tokenizers huggingface_hub transformers jinja2 sentencepiece protobuf sacremoses

      - name: Restore tokenizer fixtures
        shell: bash
        run: |
          set -euo pipefail
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          python tests/Py/Huggingface/restore_test_data.py --force

      - name: Configure Hugging Face authentication
        shell: bash
        run: |
          set -euo pipefail
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          hf_token="${{ secrets.HF_TOKEN }}"
          if [ -z "$hf_token" ]; then
            echo "HF_TOKEN secret is not configured; skipping Hugging Face login." >&2
            exit 0
          fi
          python tests/Py/Huggingface/hf_auth.py login "$hf_token"

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build TokenX.HF.sln --configuration Release --no-restore

      - name: Download test data fixtures
        shell: bash
        run: |
          set -euo pipefail
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          python tests/Py/Huggingface/download_tests_data.py

      - name: Generate benchmark corpora
        shell: bash
        run: |
          set -euo pipefail
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          python tests/Py/Huggingface/generate_benchmarks.py

      - name: Clear Hugging Face authentication
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          ACTIVATE=".venv/bin/activate"
          if [ "${RUNNER_OS}" = "Windows" ]; then
            ACTIVATE=".venv/Scripts/activate"
          fi
          . "${ACTIVATE}"
          python tests/Py/Huggingface/hf_auth.py logout

      - name: Run integration tests
        run: dotnet test TokenX.HF.sln --configuration Release --no-build --logger "trx;LogFileName=integration-tests.trx" --filter "TestCategories=Integration"

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: canary-integration-test-results-${{ matrix.os }}
          path: tests/**/TestResults/*.trx
          if-no-files-found: ignore

  pack:
    name: Pack NuGet Artifacts
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download runtime assets
        uses: actions/download-artifact@v4
        with:
          name: tokenizers-hf-runtimes
          path: runtime-assets

      - name: Restore runtime assets
        run: |
          RUNTIMES_ROOT="src/ErgoX.VecraX.ML.NLP.Tokenizers/HuggingFace"
          rm -rf "${RUNTIMES_ROOT}/runtimes"
          mkdir -p "${RUNTIMES_ROOT}"
          tar -xzf runtime-assets/tokenizers-runtimes.tar.gz -C "${RUNTIMES_ROOT}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build TokenX.HF.sln --configuration Release --no-restore

      - name: Pack NuGet artifacts
        run: dotnet pack src/ErgoX.VecraX.ML.NLP.Tokenizers/ErgoX.VecraX.ML.NLP.Tokenizers.csproj --configuration Release --no-build --output artifacts/nuget

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: canary-nuget
          path: artifacts/nuget
          if-no-files-found: error

