name: Build Multi-Platform SentencePiece

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"
  push:
    tags:
      - "v*.*.*"

env:
  CMAKE_BUILD_TYPE: Release
  BUILD_SHARED_LIBS: ON

jobs:
  # ============================================
  # Linux x64
  # ============================================
  build-linux-x64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build SentencePiece
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSPM_ENABLE_SHARED=ON
          make -j$(nproc)

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts/linux-x64/native
          copied=false
          while IFS= read -r file; do
            cp "$file" artifacts/linux-x64/native/
            copied=true
          done < <(find build -type f -name "libsentencepiece_c*.so*" -print)

          if [ "$copied" = false ]; then
            echo "❌ libsentencepiece_c not found in build output" >&2
            find build -type f -name "*sentencepiece*"
            exit 1
          fi

          # Include canonical SentencePiece library for reference
          find build -type f -name "libsentencepiece.so*" -exec cp {} artifacts/linux-x64/native/ \; || true
          ls -lh artifacts/linux-x64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-linux-x64
          path: artifacts/linux-x64/

  # ============================================
  # Windows x64
  # ============================================
  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Build SentencePiece
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release --parallel

      - name: Prepare artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifacts/win-x64/native
          # Ensure the C facade is available
          $cFacade = @(Get-ChildItem -Path build -Recurse -Filter "sentencepiece_c*.dll" -ErrorAction SilentlyContinue)
          if ($cFacade.Count -eq 0) {
            Write-Host "❌ Error: sentencepiece_c DLL not found!"
            Get-ChildItem -Path build -Recurse -Filter "*.dll" | ForEach-Object {
              Write-Host "Available DLL: $($_.FullName)"
            }
            exit 1
          }

          $cFacade | ForEach-Object {
            Copy-Item $_.FullName artifacts/win-x64/native/
            Write-Host "✅ Copied facade: $($_.Name)"
          }

          # Ship the canonical SentencePiece DLL as well when available
          $coreDlls = @(Get-ChildItem -Path build -Recurse -Filter "sentencepiece.dll" -ErrorAction SilentlyContinue)
          $coreDlls | ForEach-Object {
            Copy-Item $_.FullName artifacts/win-x64/native/ -ErrorAction SilentlyContinue
          }
          Get-ChildItem artifacts/win-x64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-win-x64
          path: artifacts/win-x64/

  # ============================================
  # macOS x64
  # ============================================
  build-macos-x64:
    name: Build macOS x64
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Build SentencePiece
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DSPM_ENABLE_SHARED=ON \
            -DCMAKE_OSX_ARCHITECTURES=x86_64
          make -j$(sysctl -n hw.ncpu)

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts/osx-x64/native
          copied=false
          while IFS= read -r file; do
            cp "$file" artifacts/osx-x64/native/
            copied=true
          done < <(find build -type f -name "libsentencepiece_c*.dylib" -print)

          if [ "$copied" = false ]; then
            echo "❌ libsentencepiece_c.dylib not found" >&2
            find build -type f -name "*sentencepiece*"
            exit 1
          fi

          find build -type f -name "libsentencepiece.dylib" -exec cp {} artifacts/osx-x64/native/ \; || true
          ls -lh artifacts/osx-x64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-osx-x64
          path: artifacts/osx-x64/

  # ============================================
  # macOS ARM64 (Apple Silicon)
  # ============================================
  build-macos-arm64:
    name: Build macOS ARM64
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Build SentencePiece
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DSPM_ENABLE_SHARED=ON \
            -DCMAKE_OSX_ARCHITECTURES=arm64
          make -j$(sysctl -n hw.ncpu)

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts/osx-arm64/native
          copied=false
          while IFS= read -r file; do
            cp "$file" artifacts/osx-arm64/native/
            copied=true
          done < <(find build -type f -name "libsentencepiece_c*.dylib" -print)

          if [ "$copied" = false ]; then
            echo "❌ libsentencepiece_c.dylib not found" >&2
            find build -type f -name "*sentencepiece*"
            exit 1
          fi

          find build -type f -name "libsentencepiece.dylib" -exec cp {} artifacts/osx-arm64/native/ \; || true
          ls -lh artifacts/osx-arm64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-osx-arm64
          path: artifacts/osx-arm64/

  # ============================================
  # Android ARM64
  # ============================================
  build-android-arm64:
    name: Build Android ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip cmake
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r26d" >> $GITHUB_ENV

      - name: Build SentencePiece
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DSPM_ENABLE_SHARED=ON \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_VERSION=21 \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
            -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
            -DCMAKE_ANDROID_STL_TYPE=c++_shared
          make -j$(nproc)

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts/android-arm64/native
          copied=false
          while IFS= read -r file; do
            cp "$file" artifacts/android-arm64/native/
            copied=true
          done < <(find build -type f -name "libsentencepiece_c*.so" -print)

          if [ "$copied" = false ]; then
            echo "❌ libsentencepiece_c.so not found" >&2
            find build -type f -name "*sentencepiece*"
            exit 1
          fi

          find build -type f -name "libsentencepiece.so" -exec cp {} artifacts/android-arm64/native/ \; || true
          ls -lh artifacts/android-arm64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-android-arm64
          path: artifacts/android-arm64/

  # ============================================
  # iOS ARM64
  # ============================================
  build-ios-arm64:
    name: Build iOS ARM64
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Build SentencePiece
        run: |
          mkdir build && cd build
          cmake .. \
            -G "Xcode" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
            -DBUILD_SHARED_LIBS=OFF \
            -DSPM_ENABLE_SHARED=OFF
          cmake --build . --config Release --parallel

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts/ios-arm64/native
          copied=false
          while IFS= read -r file; do
            cp "$file" artifacts/ios-arm64/native/
            copied=true
          done < <(find build -type f -name "libsentencepiece_c*.a" -print)

          if [ "$copied" = false ]; then
            echo "❌ libsentencepiece_c static library not found" >&2
            find build -type f -name "*sentencepiece*"
            exit 1
          fi

          find build -type f -name "libsentencepiece.a" -exec cp {} artifacts/ios-arm64/native/ \; || true
          ls -lh artifacts/ios-arm64/native/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentencepiece-ios-arm64
          path: artifacts/ios-arm64/
